language: generic
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_1d8c94bea0f3_key -iv $encrypted_1d8c94bea0f3_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod +x scripts/bootstrap.sh
script:
- bash scripts/bootstrap.sh -n
- docker-compose -f docker-compose.dev.yml -T exec -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN plantit coverage run --source='.' ./manage.py test
- docker-compose -f docker-compose.dev.yml -T exec -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN plantit coveralls
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push computationalplantscience/plantit
deploy:
- provider: script
  script: bash scripts/deploy-ssh.sh
  on:
    branch: master
  skip_cleanup: true
