language: generic
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_1d8c94bea0f3_key -iv $encrypted_1d8c94bea0f3_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod +x dev/bootstrap.sh
script:
- "./dev/bootstrap.sh"
- docker-compose -f docker-compose.yml -f docker-compose.dev.yml run plantit /code/dev/wait-for-postgres.sh postgres ./manage.py test
deploy:
- provider: script
  script: bash dev/deploy-ssh.sh
  on:
    branch: master
